import type { EraTheme, UpgradeDef, TraditionDef, StaffDef } from './gameTypes';

export const ERA_ORDER: Array<import('./gameTypes').EraId> = ['apostolic', 'monastic', 'reformation', 'modern'];

export const ERA_THEMES: Record<import('./gameTypes').EraId, EraTheme> = {
  apostolic: {
    id: 'apostolic',
    name: 'Apostolic & Desert Era',
    subtitle: 'House churches, catacombs, desert fathers',
    bg: '#0c0905',
    panelBg: '#160e06',
    panelBorder: '#3d2408',
    accent: '#c9960c',
    accentDim: '#7a5a08',
    accentText: '#ffe0a0',
    text: '#f0e0c0',
    subtext: '#8a7050',
    badgeBg: '#6b1010',
    badgeText: '#ffcfcf',
    progressFill: 'linear-gradient(90deg, #c9960c, #8b1a1a)',
    lifetimeKIRequired: 0,
  },
  monastic: {
    id: 'monastic',
    name: 'Schism & Monastic Era',
    subtitle: 'Benedictine abbeys, the Great Schism, crusades',
    bg: '#060a14',
    panelBg: '#0a1020',
    panelBorder: '#1a2e50',
    accent: '#4a78c0',
    accentDim: '#2a4880',
    accentText: '#b0ccf8',
    text: '#c8d8f0',
    subtext: '#4a6080',
    badgeBg: '#1e3a6a',
    badgeText: '#b0ccf8',
    progressFill: 'linear-gradient(90deg, #4a78c0, #8090c0)',
    lifetimeKIRequired: 5000,
  },
  reformation: {
    id: 'reformation',
    name: 'Reformation Era',
    subtitle: 'Luther, Calvin, the printing press, sola scriptura',
    bg: '#070c07',
    panelBg: '#0c160c',
    panelBorder: '#1a3018',
    accent: '#c8a020',
    accentDim: '#7a6010',
    accentText: '#f0df90',
    text: '#d8ead0',
    subtext: '#5a7050',
    badgeBg: '#1c4a1c',
    badgeText: '#a0d890',
    progressFill: 'linear-gradient(90deg, #c8a020, #2d8a2d)',
    lifetimeKIRequired: 50000,
  },
  modern: {
    id: 'modern',
    name: 'Modern Urban Frontier',
    subtitle: 'Megachurches, justice movements, digital ministry',
    bg: '#060610',
    panelBg: '#0c0c1e',
    panelBorder: '#1e1e40',
    accent: '#00c8f0',
    accentDim: '#006880',
    accentText: '#80eeff',
    text: '#d0d0ff',
    subtext: '#5050a0',
    badgeBg: '#3a1a7a',
    badgeText: '#c0a0ff',
    progressFill: 'linear-gradient(90deg, #00c8f0, #7c3aed)',
    lifetimeKIRequired: null,
  },
};

export const UPGRADES: UpgradeDef[] = [
  {
    id: 'congregation',
    name: 'Congregation',
    emoji: '🙏',
    baseCost: 100,
    passivePerUnit: 2,
    desc: 'Faithful souls gathering for worship and prayer.',
    eraRequired: 'apostolic',
  },
  {
    id: 'sanctuary',
    name: 'Sanctuary',
    emoji: '⛪',
    baseCost: 500,
    passivePerUnit: 10,
    desc: 'The sacred nave where the ekklesia assembles.',
    eraRequired: 'apostolic',
  },
  {
    id: 'outreach',
    name: 'Outreach Ministry',
    emoji: '🤲',
    baseCost: 1000,
    passivePerUnit: 8,
    desc: 'Serving the poor, widows, and the city gates.',
    eraRequired: 'apostolic',
  },
  {
    id: 'spire',
    name: 'Spire & Bell Tower',
    emoji: '🗼',
    baseCost: 2000,
    passivePerUnit: 5,
    desc: 'A beacon to heaven, calling the faithful.',
    eraRequired: 'monastic',
  },
  {
    id: 'scriptorium',
    name: 'Scriptorium',
    emoji: '📜',
    baseCost: 5000,
    passivePerUnit: 15,
    desc: 'Where monks copy Scripture and preserve theology.',
    eraRequired: 'monastic',
  },
  {
    id: 'cathedral',
    name: 'Cathedral',
    emoji: '🏰',
    baseCost: 20000,
    passivePerUnit: 50,
    desc: 'A great monument to God\'s glory and civic power.',
    eraRequired: 'reformation',
  },
  {
    id: 'multisite',
    name: 'Multi-Site Campus',
    emoji: '🏘️',
    baseCost: 50000,
    passivePerUnit: 100,
    desc: 'The Kingdom expanding to new neighborhoods.',
    eraRequired: 'modern',
  },
];

export const TRADITIONS: TraditionDef[] = [
  {
    id: 'liturgical',
    name: 'Liturgical',
    emoji: '✝️',
    desc: 'Ancient rites, sacraments, and sacred order',
    eraRequired: 'monastic',
    branches: [
      {
        id: 'orthodox',
        name: 'Eastern Orthodox',
        bonus: '+30% Scriptorium, +20% Spire KI',
        multipliers: { scriptorium: 1.3, spire: 1.2 },
        passiveBonus: 1.1,
      },
      {
        id: 'catholic',
        name: 'Roman Catholic',
        bonus: '+40% Cathedral, +20% Sanctuary KI',
        multipliers: { cathedral: 1.4, sanctuary: 1.2 },
        passiveBonus: 1.15,
      },
    ],
  },
  {
    id: 'reformation_trad',
    name: 'Reformation',
    emoji: '📖',
    desc: 'Sola Scriptura, Sola Fide, Sola Gratia',
    eraRequired: 'reformation',
    branches: [
      {
        id: 'reformed',
        name: 'Reformed/Presbyterian',
        bonus: '+50% Scriptorium, +20% Congregation KI',
        multipliers: { scriptorium: 1.5, congregation: 1.2 },
        passiveBonus: 1.1,
      },
      {
        id: 'methodist',
        name: 'Methodist/Anglican',
        bonus: '+50% Outreach, +30% Congregation KI',
        multipliers: { outreach: 1.5, congregation: 1.3 },
        passiveBonus: 1.12,
      },
    ],
  },
  {
    id: 'heritage',
    name: 'Heritage',
    emoji: '✊',
    desc: 'Prophetic, rooted, and community-driven witness',
    eraRequired: 'modern',
    branches: [
      {
        id: 'blackchurch',
        name: 'Historic Black Church',
        bonus: '+60% Outreach, +40% Congregation KI',
        multipliers: { outreach: 1.6, congregation: 1.4 },
        passiveBonus: 1.2,
      },
      {
        id: 'pentecostal',
        name: 'Pentecostal/Apostolic',
        bonus: '+70% Multi-Site, +30% Congregation KI',
        multipliers: { multisite: 1.7, congregation: 1.3 },
        passiveBonus: 1.15,
      },
    ],
  },
];

export const STAFF_DEFS: StaffDef[] = [
  {
    id: 'choirmaster',
    name: 'Choir Master / Liturgist',
    emoji: '🎵',
    costPerTick: 50,
    multipliers: { congregation: 1.2, sanctuary: 1.2 },
    desc: 'Leads liturgical music. +20% Congregation & Sanctuary KI.',
  },
  {
    id: 'intern',
    name: 'Theological Intern',
    emoji: '🎓',
    costPerTick: 30,
    multipliers: { scriptorium: 1.25 },
    desc: 'Studies systematic theology. +25% Scriptorium KI.',
  },
  {
    id: 'organizer',
    name: 'Community Organizer',
    emoji: '🤝',
    costPerTick: 40,
    multipliers: { outreach: 1.3 },
    desc: 'Mobilizes for justice work. +30% Outreach KI.',
  },
  {
    id: 'chronicler',
    name: 'Monastic Chronicler',
    emoji: '✍️',
    costPerTick: 60,
    multipliers: {
      congregation: 1.15,
      sanctuary: 1.15,
      scriptorium: 1.15,
      outreach: 1.15,
      spire: 1.15,
      cathedral: 1.15,
      multisite: 1.15,
    },
    desc: 'Records church history. +15% all upgrade KI.',
  },
];

export const MAX_STAFF = 3;
export const TICK_INTERVAL_MS = 1000;
export const HIRE_COST_BASE = 500;
